server:
  port: 8090
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.82.100
  rabbitmq:
    virtual-host: /leyou
    username: guest
    password: guest
    host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ly:
  jwt:
    pubKeyPath: C:\Users\john\bystander\id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称